export default {
  vi: {
    Sign_in_to_your_account: 'Đăng nhập bằng tài khoản của bạn',
    Sign_in: 'Đăng nhập',
    Forgot_you_password: 'Quên mật khẩu',
    Your_contacts: 'Danh bạ',
    Add_a_new_contact: 'Thêm danh bạ',
    Add_Edit_contact: 'Thêm / Sửa người liên hệ',
    Full_name: 'Tên đầy đủ',
    Phone_number: 'Số điện thoại',
    Nick_name: 'Biệt danh',
    Location: 'Vị trí',
    Settings: 'Cài đặt',
    Language: 'Ngôn ngữ',
    Themes: 'Chủ đề',
    Notification: 'Thông báo',
    Sign_out: 'Đăng xuất',
    Contacts: 'Danh bạ',
    Add: 'Thêm',
  },
  en: {
    Sign_in_to_your_account: 'Sign in to your account',
    Sign_in: 'Sign in',
    Forgot_you_password: 'Forgot you password',
    Your_contacts: 'Your contacts',
    Add_a_new_contact: 'Add a new contact',
    Add_Edit_contact: 'Add / Edit contact',
    Full_name: 'Full name',
    Phone_number: 'Phone number',
    Nick_name: 'Nick name',
    Location: 'Location',
    Settings: 'Settings',
    Language: 'Language',
    Themes: 'Themes',
    Notification: 'Notification',
    Sign_out: 'Sign out',
    Contacts: 'Contact',
    Add: 'Add',
  },
}
